name: My Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests_job:
    runs-on: ubuntu-latest
    steps:
      # Étape pour récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape pour installer Python et les dépendances si nécessaire
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

       # Ajout du cache pip
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Étape pour exécuter les tests
      - name: Run tests
        run: pytest -vv
        env:
          HOST_MONGODB: ${{ secrets.HOST_MONGODB }}
          MONGO_DB_APPNAME: ${{ secrets.MONGO_DB_APPNAME }}
          PASSWORD_MONGODB: ${{ secrets.PASSWORD_MONGODB }}
          USER_MONGODB: ${{ secrets.USER_MONGODB }}

  build:
    needs: tests_job
    runs-on: ubuntu-latest
    steps:
      # Si le job de build a aussi besoin du code, refais le checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}

