name: My Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
      - name: Run tests
        run: pytest -vv
        env:
          HOST_MONGODB: ${{ secrets.HOST_MONGODB }}
          MONGO_DB_APPNAME: ${{ secrets.MONGO_DB_APPNAME }}
          PASSWORD_MONGODB: ${{ secrets.PASSWORD_MONGODB }}
          USER_MONGODB: ${{ secrets.USER_MONGODB }}